# If it detects a version bump on main, it will trigger a release.
name: Detect version bump

on:
  push:
    branches:
      - 'main'

jobs:
  detect-version-bump:
    name: ðŸ”  Detect version bump
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test
        run: echo "${{ github.event }}"

      - name: ðŸ” Check if version changed
        uses: EndBug/version-check@v1
        id: check

      - name: âœ… Version bump detected
        if: steps.check.outputs.changed == 'true'
        run: echo "Version bump detected, triggering release workflow âœ…"

  release:
    name: Create GitHub release and publish to NPM
    runs-on: ubuntu-latest
    # if: steps.check.outputs.changed == 'true'
    needs: detect-version-bump
    steps:
      - name: Force main branch
        if: github.ref != 'refs/heads/main'
        run: |-
          echo "Not running on main - exit"
          exit 1

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@erc725'
          cache: 'npm'

      - name: Set Version
        run: |-
          APP_VERSION="v$(node -pe "require('./package.json').version")"
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Install
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      # Create GitHub Release
      - name: Extract release notes from CHANGELOG
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
        with:
          release_notes_file: RELEASENOTES.md

      - uses: ncipollo/release-action@v1
        with:
          bodyFile: 'RELEASENOTES.md'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.APP_VERSION }}

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
