# If it detects a version bump on main, it will trigger a release.
name: Detect version bump

on:
  push:
    branches:
      - 'main'

jobs:
  detect-version-bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ğŸ” Check if version changed
        uses: EndBug/version-check@v1
        id: check

      - name: âœ… Version bump detected
        if: steps.check.outputs.changed == 'true'
        run: echo "Version bump detected, triggering release workflow âœ…"

      # Trigger Release
      - name: ğŸš€ Repository dispatch trigger-release
        if: steps.check.outputs.changed == 'true'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
